apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterreaders.clusterreader.sre.openshift.com
spec:
  group: clusterreader.sre.openshift.com
  names:
    kind: ClusterReader
    listKind: ClusterReaderList
    plural: clusterreaders
    singular: clusterreader
  scope: Cluster
  version: v1alpha1
